In [1]:
import pandas as pd
df = pd.read_csv('DCh-Miner_miner-disease-chemical.tsv',sep='\t')

In [2]:
df.iloc[:, 0] = [i[5:] for i in df.iloc[:,0]]

In [3]:
df

       # Disease(MESH) Chemical
0              D005923  DB00564
1              D009503  DB01072
2              D016115  DB01759
3              D018476  DB00451
4              C567059  DB00641
...                ...      ...
466652         C565545  DB00482
466653         D009164  DB00977
466654         D010518  DB04216
466655         D002653  DB02701
466656         D013119  DB04465

[466657 rows x 2 columns]

In [4]:
drug_df = pd.read_csv('processed_drug_simmat.csv', index_col=0)
disease_df = pd.read_csv('processed_disease_simmat.csv', index_col=0)

drug_names = drug_df.index
disease_names = disease_df.index

In [5]:
df[df['Chemical'] == 'D018784']

Empty DataFrame
Columns: [# Disease(MESH), Chemical]
Index: []

In [6]:
disease_names

Index(['D017088', 'D018784', 'D000014', 'D000022', 'D000038', 'D015823',
       'D000151', 'D000152', 'D000163', 'D000172',
       ...
       'D014717', 'D014777', 'D014839', 'D014860', 'D014901', 'D014927',
       'D014946', 'D014987', 'D015043', 'D020096'],
      dtype='object', length=638)

In [7]:
len(drug_names)

587

In [8]:
len(set(df.iloc[:,1]))
len(drug_names)

587

In [9]:
len(set(df.iloc[:,0]))
len(disease_names)

638

In [10]:
df = df[df['Chemical'].isin(drug_names)]
df = df[df['# Disease(MESH)'].isin(disease_names)]
df

       # Disease(MESH) Chemical
1              D009503  DB01072
8              D001249  DB00814
11             D009325  DB00851
16             D001281  DB01394
18             D010391  DB00515
...                ...      ...
466634         D015212  DB00669
466639         D018276  DB00533
466642         D000707  DB00281
466651         D015228  DB00114
466653         D009164  DB00977

[75919 rows x 2 columns]

In [11]:
interaction_set = set([(i['# Disease(MESH)'],i['Chemical']) for j,i in df.iterrows()])
interaction_set

{('D018487', 'DB00843'),
 ('D002311', 'DB00570'),
 ('D008223', 'DB00675'),
 ('D001714', 'DB00122'),
 ('D018805', 'DB00682'),
 ('D001929', 'DB01008'),
 ('D007247', 'DB00813'),
 ('D006258', 'DB01085'),
 ('D018805', 'DB00193'),
 ('D009203', 'DB01073'),
 ('D011565', 'DB00949'),
 ('D012140', 'DB01115'),
 ('D006177', 'DB01356'),
 ('D012514', 'DB00491'),
 ('D008223', 'DB00982'),
 ('D009336', 'DB00695'),
 ('D007319', 'DB00334'),
 ('D016780', 'DB00608'),
 ('D003928', 'DB00530'),
 ('D001321', 'DB00871'),
 ('D004617', 'DB00541'),
 ('D012871', 'DB00165'),
 ('D014657', 'DB00307'),
 ('D001943', 'DB00175'),
 ('D005221', 'DB00390'),
 ('D013274', 'DB01162'),
 ('D020734', 'DB01378'),
 ('D019970', 'DB00733'),
 ('D001943', 'DB00468'),
 ('D011471', 'DB00630'),
 ('D014839', 'DB00305'),
 ('D009165', 'DB00822'),
 ('D012772', 'DB00333'),
 ('D002100', 'DB00441'),
 ('D010673', 'DB01115'),
 ('D006086', 'DB00636'),
 ('D004427', 'DB00091'),
 ('D012871', 'DB00445'),
 ('D009362', 'DB00367'),
 ('D013964', 'DB01189'),
 ('D005221', 'DB00334'),
 ('D006501', 'DB00122'),
 ('D016055', 'DB01151'),
 ('D006470', 'DB00584'),
 ('D002100', 'DB01222'),
 ('D009447', 'DB01590'),
 ('D008545', 'DB00544'),
 ('D002294', 'DB00357'),
 ('D000172', 'DB00104'),
 ('D003093', 'DB01254'),
 ('D011018', 'DB00622'),
 ('D018805', 'DB00335'),
 ('D014202', 'DB00794'),
 ('D001929', 'DB00175'),
 ('D009393', 'DB00630'),
 ('D012848', 'DB00472'),
 ('D009059', 'DB00624'),
 ('D009369', 'DB00871'),
 ('D012772', 'DB00290'),
 ('D007249', 'DB01095'),
 ('D010195', 'DB00357'),
 ('D010698', 'DB00227'),
 ('D016908', 'DB00983'),
 ('D017119', 'DB00328'),
 ('D003490', 'DB00575'),
 ('D006951', 'DB00428'),
 ('D009376', 'DB00717'),
 ('D000789', 'DB00396'),
 ('D012563', 'DB00408'),
 ('D006976', 'DB00624'),
 ('D014777', 'DB00586'),
 ('D003093', 'DB00398'),
 ('D007674', 'DB00734'),
 ('D006261', 'DB00661'),
 ('D011565', 'DB00669'),
 ('D054198', 'DB01156'),
 ('D000690', 'DB00437'),
 ('D003876', 'DB00829'),
 ('D007003', 'DB00627'),
 ('D006966', 'DB01577'),
 ('D012516', 'DB00396'),
 ('D007003', 'DB00814'),
 ('D012848', 'DB00550'),
 ('D014552', 'DB01351'),
 ('D003929', 'DB00264'),
 ('D005901', 'DB00605'),
 ('D006967', 'DB00695'),
 ('D003924', 'DB00635'),
 ('D010190', 'DB00712'),
 ('D003248', 'DB00397'),
 ('D011471', 'DB00204'),
 ('D020820', 'DB00273'),
 ('D009362', 'DB00537'),
 ('D004487', 'DB01400'),
 ('D008113', 'DB00571'),
 ('D001778', 'DB00758'),
 ('D000855', 'DB00594'),
 ('D007022', 'DB00908'),
 ('D006501', 'DB00776'),
 ('D001281', 'DB00661'),
 ('D002277', 'DB01394'),
 ('D002289', 'DB01058'),
 ('D005334', 'DB00297'),
 ('D001749', 'DB00882'),
 ('D018357', 'DB01030'),
 ('D002280', 'DB01241'),
 ('D012220', 'DB00419'),
 ('D001932', 'DB02546'),
 ('D008175', 'DB00188'),
 ('D006967', 'DB00203'),
 ('D000022', 'DB00555'),
 ('D013375', 'DB01275'),
 ('D012595', 'DB00661'),
 ('D014456', 'DB00208'),
 ('D017714', 'DB00199'),
 ('D003929', 'DB01029'),
 ('D013920', 'DB00554'),
 ('D011565', 'DB01576'),
 ('D016584', 'DB00091'),
 ('D012640', 'DB00555'),
 ('D010146', 'DB01242'),
 ('D019970', 'DB00763'),
 ('D054198', 'DB00468'),
 ('D004830', 'DB00382'),
 ('D007006', 'DB01259'),
 ('D001014', 'DB00762'),
 ('D003093', 'DB00136'),
 ('D002690', 'DB01137'),
 ('D000022', 'DB00268'),
 ('D014549', 'DB00747'),
 ('D015451', 'DB01275'),
 ('D002294', 'DB00650'),
 ('D003480', 'DB00215'),
 ('D001172', 'DB00586'),
 ('D062787', 'DB00515'),
 ('D009461', 'DB00763'),
 ('D010148', 'DB00218'),
 ('D008545', 'DB01189'),
 ('D008105', 'DB00328'),
 ('D002294', 'DB00907'),
 ('D001943', 'DB01221'),
 ('D003320', 'DB01069'),
 ('D009404', 'DB00636'),
 ('D010195', 'DB00650'),
 ('D001327', 'DB01216'),
 ('D012640', 'DB00268'),
 ('D004381', 'DB00201'),
 ('D011537', 'DB01223'),
 ('D012208', 'DB01356'),
 ('D002690', 'DB00822'),
 ('D012772', 'DB01395'),
 ('D002311', 'DB00759'),
 ('D003876', 'DB01394'),
 ('D001014', 'DB00484'),
 ('D010195', 'DB00907'),
 ('D000544', 'DB01098'),
 ('D001281', 'DB00286'),
 ('D015877', 'DB00636'),
 ('D001145', 'DB00404'),
 ('D012514', 'DB01219'),
 ('D021441', 'DB00590'),
 ('D002294', 'DB00563'),
 ('D016410', 'DB00140'),
 ('D010003', 'DB00363'),
 ('D004443', 'DB00960'),
 ('D005764', 'DB00428'),
 ('D006323', 'DB01364'),
 ('D016778', 'DB00977'),
 ('D004715', 'DB00936'),
 ('D020521', 'DB01173'),
 ('D003110', 'DB01367'),
 ('D012983', 'DB00441'),
 ('D004381', 'DB00388'),
 ('D001929', 'DB01221'),
 ('D007674', 'DB00571'),
 ('D001749', 'DB00381'),
 ('D002294', 'DB00532'),
 ('D009765', 'DB00717'),
 ('D002311', 'DB01045'),
 ('D004417', 'DB00988'),
 ('D017119', 'DB00541'),
 ('D018276', 'DB00977'),
 ('D002545', 'DB00707'),
 ('D012640', 'DB01238'),
 ('D009128', 'DB01221'),
 ('D012983', 'DB01222'),
 ('D002289', 'DB00898'),
 ('D064420', 'DB01018'),
 ('D003093', 'DB00477'),
 ('D004715', 'DB00918'),
 ('D005909', 'DB00281'),
 ('D012559', 'DB00831'),
 ('D006937', 'DB00284'),
 ('D016055', 'DB00999'),
 ('D007006', 'DB00413'),
 ('D015464', 'DB00763'),
 ('D001932', 'DB00584'),
 ('D054198', 'DB00540'),
 ('D001172', 'DB00412'),
 ('D009103', 'DB01030'),
 ('D001281', 'DB00958'),
 ('D001014', 'DB00177'),
 ('D054198', 'DB00917'),
 ('D002277', 'DB01296'),
 ('D012128', 'DB00990'),
 ('D013274', 'DB01076'),
 ('D002100', 'DB00530'),
 ('D020246', 'DB00316'),
 ('D000544', 'DB00514'),
 ('D012128', 'DB00451'),
 ('D012128', 'DB00457'),
 ('D008088', 'DB00230'),
 ('D011704', 'DB00624'),
 ('D006976', 'DB00871'),
 ('D008180', 'DB00907'),
 ('D011656', 'DB00966'),
 ('D001714', 'DB00533'),
 ('D004485', 'DB00126'),
 ('D006086', 'DB00337'),
 ('D011018', 'DB00712'),
 ('D009798', 'DB00255'),
 ('D011183', 'DB00286'),
 ('D014605', 'DB00999'),
 ('D011565', 'DB00593'),
 ('D017449', 'DB00741'),
 ('D003248', 'DB01017'),
 ('D006973', 'DB00514'),
 ('D008175', 'DB00995'),
 ('D003924', 'DB01216'),
 ('D012559', 'DB00903'),
 ('D003424', 'DB00328'),
 ('D013276', 'DB00762'),
 ('D013921', 'DB00882'),
 ('D008607', 'DB00091'),
 ('D006967', 'DB00763'),
 ('D002100', 'DB01069'),
 ('D013375', 'DB00206'),
 ('D001714', 'DB00091'),
 ('D005902', 'DB00465'),
 ('D016778', 'DB00669'),
 ('D012514', 'DB00795'),
 ('D012140', 'DB00264'),
 ('D005759', 'DB00563'),
 ('D005334', 'DB00443'),
 ('D005902', 'DB01132'),
 ('D003928', 'DB00428'),
 ('D010149', 'DB00661'),
 ('D002294', 'DB00796'),
 ('D012893', 'DB00636'),
 ('D002289', 'DB00623'),
 ('D013964', 'DB00297'),
 ('D001249', 'DB01064'),
 ('D012772', 'DB00523'),
 ('D007249', 'DB00594'),
 ('D006501', 'DB00533'),
 ('D007898', 'DB00655'),
 ('D010996', 'DB01427'),
 ('D008585', 'DB00316'),
 ('D001778', 'DB00278'),
 ('D018754', 'DB00480'),
 ('D012516', 'DB00714'),
 ('D009765', 'DB00305'),
 ('D004487', 'DB00515'),
 ('D010195', 'DB00796'),
 ('D016649', 'DB00860'),
 ('D006261', 'DB01151'),
 ('D015451', 'DB00206'),
 ('D001749', 'DB00668'),
 ('D013274', 'DB00612'),
 ('D013203', 'DB02546'),
 ('D012509', 'DB00696'),
 ('D004443', 'DB00762'),
 ('D014257', 'DB00727'),
 ('D014839', 'DB00458'),
 ('D004832', 'DB00908'),
 ('D001327', 'DB00397'),
 ('D014839', 'DB00575'),
 ('D006501', 'DB00091'),
 ('D064420', 'DB00559'),
 ('D006509', 'DB00515'),
 ('D002545', 'DB00678'),
 ('D012770', 'DB01204'),
 ('D007247', 'DB00169'),
 ('D003866', 'DB00361'),
 ('D007680', 'DB00323'),
 ('D002294', 'DB00790'),
 ('D010190', 'DB00860'),
 ('D004715', 'DB00203'),
 ('D006996', 'DB00313'),
 ('D007676', 'DB01169'),
 ('D015228', 'DB00436'),
 ('D003093', 'DB00422'),
 ('D010146', 'DB00953'),
 ('D006470', 'DB00959'),
 ('D010195', 'DB00790'),
 ('D010300', 'DB01233'),
 ('D007634', 'DB00907'),
 ('D010014', 'DB01232'),
 ('D008175', 'DB00640'),
 ('D004715', 'DB00733'),
 ('D012140', 'DB01029'),
 ('D000855', 'DB00947'),
 ('D004938', 'DB01261'),
 ('D007022', 'DB00544'),
 ('D011125', 'DB00285'),
 ('D007896', 'DB00741'),
 ('D004751', 'DB01204'),
 ('D009362', 'DB01039'),
 ('D013276', 'DB00177'),
 ('D009362', 'DB00199'),
 ('D000014', 'DB00999'),
 ('D008088', 'DB01128'),
 ('D017116', 'DB00957'),
 ('D008269', 'DB01050'),
 ('D008288', 'DB00695'),
 ('D009165', 'DB01016'),
 ('D012772', 'DB00227'),
 ('D015212', 'DB00747'),
 ('D008180', 'DB00796'),
 ('D016481', 'DB00441'),
 ('D003550', 'DB01165'),
 ('D013927', 'DB00169'),
 ('D011654', 'DB00851'),
 ('D010051', 'DB00853'),
 ('D018805', 'DB00939'),
 ('D000437', 'DB00328'),
 ('D000022', 'DB01129'),
 ('D019966', 'DB01577'),
 ('D011654', 'DB00471'),
 ('D001049', 'DB00333'),
 ('D000402', 'DB00182'),
 ('D009165', 'DB01203'),
 ('D009325', 'DB00281'),
 ('D016481', 'DB01222'),
 ('D001014', 'DB01275'),
 ('D006932', 'DB00843'),
 ('D011141', 'DB01181'),
 ('D019970', 'DB00764'),
 ('D013921', 'DB00428'),
 ('D006073', 'DB01041'),
 ('D000544', 'DB01110'),
 ('D002292', 'DB01235'),
 ('D011833', 'DB00586'),
 ('D002280', 'DB00334'),
 ('D011471', 'DB00179'),
 ('D012640', 'DB01129'),
 ('D001171', 'DB00679'),
 ('D006961', 'DB01229'),
 ('D009765', 'DB00536'),
 ('D004443', 'DB00177'),
 ('D008223', 'DB01204'),
 ('D020246', 'DB00182'),
 ('D012871', 'DB00741'),
 ('D000855', 'DB00909'),
 ('D007172', 'DB00181'),
 ('D009404', 'DB00337'),
 ('D006261', 'DB01406'),
 ('D004830', 'DB01200'),
 ('D003924', 'DB00397'),
 ('D001008', 'DB00717'),
 ('D006973', 'DB01110'),
 ('D020329', 'DB01356'),
 ('D003424', 'DB01083'),
 ('D012120', 'DB00755'),
 ('D011618', 'DB00747'),
 ('D010787', 'DB00537'),
 ('D015473', 'DB00882'),
 ('D011565', 'DB01378'),
 ('D013203', 'DB00584'),
 ('D016889', 'DB00441'),
 ('D003424', 'DB00541'),
 ('D006966', 'DB00864'),
 ('D008113', 'DB00180'),
 ('D012983', 'DB00530'),
 ('D005158', 'DB00482'),
 ('D001321', 'DB00758'),
 ('D008545', 'DB00297'),
 ('D014456', 'DB00544'),
 ('D007247', 'DB00497'),
 ('D012770', 'DB00445'),
 ('D011656', 'DB00379'),
 ('D006961', 'DB00321'),
 ('D006333', 'DB00808'),
 ('D008113', 'DB00968'),
 ('D007964', 'DB00388'),
 ('D013924', 'DB01196'),
 ('D016889', 'DB01222'),
 ('D015179', 'DB01235'),
 ('D004827', 'DB00762'),
 ('D000505', 'DB00679'),
 ('D011595', 'DB00277'),
 ('D016649', 'DB00675'),
 ('D006938', 'DB00773'),
 ('D004487', 'DB00983'),
 ('D002289', 'DB01118'),
 ('D002294', 'DB01005'),
 ('D010300', 'DB00182'),
 ('D001145', 'DB00215'),
 ('D002690', 'DB01240'),
 ('D012983', 'DB01069'),
 ('D010014', 'DB00588'),
 ('D001172', 'DB00307'),
 ('D007247', 'DB00908'),
 ('D013921', 'DB00668'),
 ('D007249', 'DB00822'),
 ('D014397', 'DB02546'),
 ('D011833', 'DB00412'),
 ('D007634', 'DB00796'),
 ('D007676', 'DB00180'),
 ('D007003', 'DB01241'),
 ('D002292', 'DB00641'),
 ('D013964', 'DB00443'),
 ('D002545', 'DB01033'),
 ('D004487', 'DB01085'),
 ('D004827', 'DB00484'),
 ('D004942', 'DB00515'),
 ('D002547', 'DB01064'),
 ('D009203', 'DB00903'),
 ('D008088', 'DB00399'),
 ('D007022', 'DB01189'),
 ('D004715', 'DB00763'),
 ('D012772', 'DB00988'),
 ('D002545', 'DB00945'),
 ('D008607', 'DB00230'),
 ('D002545', 'DB00490'),
 ('D008180', 'DB00655'),
 ('D012893', 'DB01076'),
 ('D006258', 'DB01181'),
 ('D016870', 'DB00563'),
 ('D006689', 'DB01296'),
 ('D006509', 'DB01085'),
 ('D001327', 'DB01017'),
 ('D003110', 'DB01275'),
 ('D002056', 'DB00829'),
 ('D010051', 'DB00542'),
 ('D003872', 'DB01169'),
 ('D020734', 'DB00598'),
 ('D018589', 'DB00563'),
 ('D002289', 'DB00304'),
 ('D007674', 'DB01231'),
 ('D006261', 'DB00999'),
 ('D000022', 'DB00491'),
 ('D013276', 'DB01275'),
 ('D002690', 'DB01013'),
 ('D001008', 'DB00305'),
 ('D004715', 'DB00356'),
 ('D001749', 'DB00262'),
 ('D019966', 'DB00715'),
 ('D011018', 'DB00860'),
 ('D008223', 'DB00445'),
 ('D006967', 'DB00764'),
 ('D001171', 'DB00338'),
 ('D018589', 'DB00532'),
 ('D004487', 'DB01677'),
 ('D015179', 'DB00641'),
 ('D014839', 'DB01410'),
 ('D058186', 'DB00407'),
 ('D001171', 'DB00749'),
 ('D020521', 'DB01254'),
 ('D001049', 'DB01068'),
 ('D012141', 'DB00563'),
 ('D012640', 'DB00491'),
 ('D012004', 'DB00305'),
 ('D005221', 'DB01030'),
 ('D000437', 'DB01083'),
 ('D009798', 'DB00554'),
 ('D002100', 'DB00428'),
 ('D004827', 'DB00177'),
 ('D008545', 'DB00397'),
 ('D020250', 'DB00757'),
 ('D004342', 'DB01394'),
 ('D000437', 'DB00541'),
 ('D006501', 'DB00230'),
 ('D007676', 'DB01202'),
 ('D014657', 'DB00977'),
 ('D015473', 'DB00428'),
 ('D003704', 'DB00907'),
 ('D001281', 'DB00999'),
 ('D003693', 'DB00819'),
 ('D007674', 'DB00180'),
 ('D008113', 'DB00481'),
 ('D001932', 'DB00959'),
 ('D020521', 'DB00398'),
 ('D004443', 'DB01275'),
 ('D007024', 'DB00458'),
 ('D007249', 'DB00947'),
 ('D007674', 'DB00968'),
 ('D004381', 'DB03796'),
 ('D012893', 'DB00612'),
 ('D011833', 'DB01174'),
 ('D000505', 'DB00338'),
 ('D015663', 'DB00338'),
 ('D007172', 'DB00448'),
 ('D009157', 'DB00564'),
 ('D002294', 'DB00332'),
 ('D012208', 'DB00316'),
 ('D006130', 'DB01234'),
 ('D014549', 'DB00537'),
 ('D017180', 'DB00679'),
 ('D008288', 'DB00763'),
 ('D010300', 'DB01403'),
 ('D002311', 'DB00755'),
 ('D004832', 'DB00544'),
 ('D000855', 'DB00501'),
 ('D012120', 'DB01234'),
 ('D007676', 'DB03904'),
 ('D001289', 'DB00413'),
 ('D006073', 'DB00583'),
 ('D013119', 'DB01098'),
 ('D018487', 'DB00679'),
 ('D009798', 'DB00398'),
 ('D002544', 'DB01076'),
 ('D012221', 'DB00122'),
 ('D007172', 'DB00863'),
 ('D009103', 'DB01120'),
 ('D014397', 'DB00584'),
 ('D007248', 'DB01394'),
 ('D011141', 'DB00499'),
 ('D005128', 'DB00323'),
 ('D007642', 'DB00363'),
 ('D006978', 'DB01118'),
 ('D007898', 'DB00912'),
 ('D004927', 'DB01394'),
 ('D008607', 'DB01128'),
 ('D001749', 'DB01142'),
 ('D016481', 'DB00530'),
 ('D007249', 'DB00909'),
 ('D009362', 'DB00927'),
 ('D001749', 'DB00363'),
 ('D003027', 'DB01356'),
 ('D006501', 'DB00710'),
 ('D011225', 'DB00441'),
 ('D019970', 'DB01050'),
 ('D003556', 'DB01050'),
 ('D009765', 'DB00575'),
 ('D007008', 'DB00773'),
 ('D002056', 'DB01394'),
 ('D004942', 'DB00983'),
 ('D011183', 'DB00999'),
 ('D000855', 'DB01016'),
 ('D013923', 'DB00624'),
 ('D020246', 'DB00007'),
 ('D006934', 'DB00273'),
 ('D006323', 'DB01229'),
 ('D004806', 'DB00898'),
 ('D004381', 'DB00724'),
 ('D014693', 'DB01200'),
 ('D011552', 'DB00541'),
 ('D054198', 'DB01058'),
 ('D020521', 'DB00136'),
 ('D004941', 'DB00499'),
 ('D002547', 'DB00277'),
 ('D008654', 'DB01262'),
 ('D000172', 'DB00091'),
 ('D003110', 'DB00206'),
 ('D000309', 'DB00371'),
 ('D009103', 'DB00537'),
 ('D013226', 'DB00555'),
 ('D007674', 'DB03904'),
 ('D003693', 'DB00193'),
 ('D001327', 'DB00277'),
 ('D009336', 'DB01050'),
 ('D016889', 'DB00530'),
 ('D006470', 'DB00328'),
 ('D013274', 'DB01268'),
 ('D009404', 'DB00744'),
 ('D013276', 'DB00206'),
 ('D006323', 'DB00321'),
 ('D009369', 'DB00831'),
 ('D014648', 'DB01169'),
 ('D006086', 'DB00863'),
 ('D012140', 'DB00501'),
 ('D013921', 'DB00262'),
 ('D014397', 'DB01098'),
 ('D014552', 'DB00586'),
 ('D001321', 'DB01262'),
 ('D009376', 'DB00126'),
 ('D004342', 'DB01296'),
 ('D008103', 'DB00675'),
 ('D010300', 'DB00007'),
 ('D017180', 'DB00338'),
 ('D004827', 'DB01275'),
 ('D002280', 'DB00966'),
 ('D012512', 'DB00747'),
 ('D013226', 'DB00268'),
 ('D017449', 'DB00695'),
 ('D012509', 'DB00675'),
 ('D005909', 'DB00477'),
 ('D003925', 'DB00252'),
 ('D008103', 'DB00982'),
 ('D006976', 'DB00758'),
 ('D003929', 'DB00570'),
 ('D006258', 'DB00499'),
 ('D020176', 'DB00564'),
 ('D004942', 'DB01075'),
 ('D001749', 'DB00622'),
 ('D006976', 'DB00214'),
 ('D008113', 'DB00783'),
 ('D018487', 'DB00338'),
 ('D012509', 'DB00982'),
 ('D004938', 'DB01030'),
 ('D011833', 'DB00307'),
 ('D015464', 'DB01050'),
 ('D016584', 'DB00907'),
 ('D003693', 'DB00335'),
 ('D011471', 'DB00218'),
 ('D009369', 'DB00903'),
 ('D007680', 'DB00588'),
 ('D020521', 'DB00477'),
 ('D008545', 'DB01017'),
 ('D012559', 'DB00585'),
 ('D004417', 'DB00584'),
 ('D013375', 'DB00451'),
 ('D000022', 'DB01219'),
 ('D012120', 'DB01136'),
 ('D002292', 'DB01115'),
 ('D007247', 'DB00544'),
 ('D015212', 'DB00367'),
 ('D010996', 'DB00820'),
 ('D008607', 'DB00399'),
 ('D013226', 'DB01238'),
 ('D000787', 'DB02546'),
 ('D007248', 'DB01296'),
 ('D004381', 'DB00997'),
 ('D003490', 'DB01182'),
 ('D014605', 'DB01232'),
 ('D004715', 'DB00764'),
 ('D012640', 'DB01219'),
 ('D017449', 'DB00203'),
 ('D007676', 'DB00783'),
 ('D013345', 'DB00936'),
 ('D015663', 'DB00394'),
 ('D005909', 'DB00325'),
 ('D006967', 'DB01050'),
 ('D004381', 'DB00975'),
 ('D003294', 'DB00186'),
 ('D000544', 'DB00549'),
 ('D013203', 'DB00959'),
 ('D004941', 'DB01095'),
 ('D013920', 'DB00412'),
 ('D015470', 'DB00655'),
 ('D000690', 'DB00717'),
 ('D012640', 'DB01124'),
 ('D019966', 'DB00864'),
 ('D015451', 'DB00451'),
 ('D002653', 'DB00907'),
 ('D014552', 'DB00412'),
 ('D003924', 'DB00277'),
 ('D013927', 'DB01229'),
 ('D014103', 'DB01156'),
 ('D054198', 'DB00898'),
 ('D001145', 'DB01105'),
 ('D007022', 'DB00297'),
 ('D006973', 'DB00549'),
 ('D018288', 'DB00773'),
 ('D015179', 'DB01115'),
 ('D014257', 'DB00428'),
 ('D007003', 'DB00334'),
 ('D010698', 'DB01098'),
 ('D007024', 'DB01410'),
 ('D013921', 'DB01142'),
 ('D009290', 'DB00624'),
 ('D013345', 'DB00776'),
 ('D007680', 'DB00983'),
 ('D006501', 'DB00399'),
 ('D003925', 'DB00788'),
 ('D003967', 'DB00851'),
 ('D001477', 'DB00783'),
 ('D013345', 'DB00692'),
 ('D006929', 'DB00396'),
 ('D012893', 'DB00744'),
 ('D003704', 'DB00655'),
 ('D009461', 'DB00958'),
 ('D006606', 'DB01235'),
 ('D015212', 'DB00537'),
 ('D000544', 'DB01192'),
 ('D004830', 'DB00252'),
 ('D011654', 'DB00361'),
 ('D013927', 'DB00321'),
 ('D001157', 'DB00696'),
 ('D012559', 'DB00285'),
 ('D014581', 'DB00182'),
 ('D007898', 'DB00747'),
 ('D058186', 'DB00178'),
 ('D019226', 'DB00624'),
 ('D005909', 'DB00470'),
 ('D008599', 'DB01406'),
 ('D012852', 'DB00959'),
 ('D006323', 'DB00635'),
 ('D008103', 'DB00996'),
 ('D000022', 'DB00795'),
 ('D002292', 'DB00829'),
 ('D009765', 'DB00816'),
 ('D007674', 'DB00783'),
 ('D013119', 'DB00959'),
 ('D001172', 'DB00619'),
 ('D009059', 'DB00252'),
 ('D013964', 'DB00991'),
 ('D005767', 'DB01143'),
 ('D008288', 'DB00764'),
 ('D009765', 'DB01410'),
 ('D004409', 'DB00675'),
 ('D011654', 'DB00353'),
 ('D000544', 'DB00295'),
 ('D006470', 'DB00541'),
 ('D009404', 'DB00863'),
 ('D001008', 'DB00575'),
 ('D012770', 'DB00741'),
 ('D003324', 'DB00441'),
 ('D011537', 'DB01169'),
 ('D012640', 'DB00795'),
 ('D015473', 'DB00262'),
 ('D007249', 'DB01016'),
 ('D004409', 'DB00982'),
 ('D003704', 'DB01005'),
 ('D012871', 'DB00695'),
 ('D007896', 'DB00203'),
 ('D020521', 'DB00422'),
 ('D001327', 'DB01001'),
 ('D004827', 'DB00206'),
 ('D006973', 'DB00295'),
 ('D000690', 'DB00305'),
 ('D003324', 'DB01222'),
 ('D001749', 'DB01023'),
 ('D004935', 'DB00721'),
 ('D006323', 'DB00657'),
 ('D009127', 'DB01080'),
 ('D000787', 'DB00584'),
 ('D001943', 'DB00861'),
 ('D062787', 'DB01181'),
 ('D020268', 'DB00675'),
 ('D011471', 'DB00887'),
 ('D007172', 'DB00310'),
 ('D015179', 'DB00829'),
 ('D015464', 'DB00958'),
 ('D015451', 'DB00014'),
 ('D003324', 'DB00993'),
 ('D013771', 'DB00636'),
 ('D000437', 'DB00956'),
 ('D011041', 'DB00140'),
 ('D019970', 'DB00647'),
 ('D003876', 'DB01165'),
 ('D009765', 'DB00721'),
 ('D004938', 'DB00461'),
 ('D011471', 'DB00573'),
 ('D001932', 'DB00328'),
 ('D008113', 'DB00472'),
 ('D002289', 'DB00333'),
 ('D006937', 'DB00331'),
 ('D002280', 'DB00379'),
 ('D001321', 'DB00813'),
 ('D008113', 'DB00806'),
 ('D002311', 'DB01136'),
 ('D004830', 'DB00788'),
 ('D014987', 'DB01142'),
 ('D001748', 'DB00695'),
 ('D012480', 'DB01165'),
 ('D007943', 'DB01229'),
 ('D001157', 'DB00126'),
 ('D001932', 'DB00549'),
 ('D001929', 'DB00861'),
 ('D001161', 'DB01174'),
 ('D012772', 'DB02546'),
 ('D007249', 'DB00302'),
 ('D008105', 'DB00201'),
 ('D011008', 'DB00477'),
 ('D012221', 'DB00091'),
 ('D007938', 'DB00441'),
 ('D017449', 'DB00763'),
 ('D005764', 'DB00712'),
 ('D002294', 'DB00921'),
 ('D006333', 'DB00636'),
 ('D006967', 'DB00958'),
 ('D002277', 'DB00514'),
 ('D016481', 'DB00428'),
 ('D003929', 'DB00759'),
 ('D004714', 'DB01064'),
 ('D011629', 'DB00966'),
 ('D002289', 'DB00290'),
 ('D009393', 'DB00573'),
 ('D009059', 'DB00788'),
 ('D006976', 'DB00278'),
 ('D007938', 'DB01222'),
 ('D064420', 'DB00382'),
 ('D003872', 'DB00783'),
 ('D007024', 'DB00692'),
 ('D005221', 'DB00245'),
 ('D009325', 'DB00325'),
 ('D007676', 'DB00472'),
 ('D004381', 'DB00364'),
 ('D008105', 'DB00388'),
 ('D000163', 'DB00636'),
 ('D010538', 'DB00549'),
 ('D020250', 'DB01069'),
 ('D009376', 'DB00694'),
 ('D009059', 'DB01262'),
 ('D005334', 'DB01041'),
 ('D003929', 'DB01045'),
 ('D011565', 'DB00808'),
 ('D009103', 'DB01039'),

In [12]:
drug_df = pd.read_csv('processed_drug_simmat.csv', index_col=0)
disease_df = pd.read_csv('processed_disease_simmat.csv', index_col=0)

drug_names = drug_df.index
disease_names = disease_df.index

In [13]:
from random import randint

non_interaction_set = set()

while len(non_interaction_set) != 76000:
    random_integer = randint(0, len(drug_names)-1)
    drug = (drug_names[random_integer])
    random_integer = randint(0, len(disease_names)-1)
    disease = (disease_names[random_integer])
    if (drug,disease) not in interaction_set:
        non_interaction_set.add((disease,drug))

In [14]:
non_interaction_list = list(non_interaction_set)
interaction_list = list(interaction_set)

non_interaction_df = pd.DataFrame(non_interaction_list) 
non_interaction_df[2] = [0]*len(non_interaction_df)

interaction_df = pd.DataFrame(interaction_list) 
interaction_df[2] = [1]*len(interaction_df)

df_concatenated = pd.concat([non_interaction_df, interaction_df], axis=0)
df_concatenated

             0        1  2
0      D018487  DB00843  0
1      D003704  DB00557  0
2      D007815  DB04844  0
3      D002056  DB00464  0
4      D017088  DB00749  0
...        ...      ... ..
75914  D017180  DB00843  1
75915  D003866  DB00285  1
75916  D008654  DB00871  1
75917  D007896  DB00445  1
75918  D002690  DB00928  1

[151919 rows x 3 columns]

In [57]:
# df_concatenated.to_csv('labels1.csv')

In [16]:
import random

interaction_list = list(interaction_set)

# Set the random seed for reproducibility (optional)
random.seed(42)

# Shuffle the list
random.shuffle(interaction_list)


selected_interactions = interaction_list[:5000]

In [17]:
non_interaction_list = list(non_interaction_set)

# Set the random seed for reproducibility (optional)
random.seed(42)

# Shuffle the list
random.shuffle(non_interaction_list)


selected_non_interactions = non_interaction_list[:5000]

In [18]:
non_interaction_list = selected_non_interactions
interaction_list = selected_interactions

non_interaction_df = pd.DataFrame(non_interaction_list) 
non_interaction_df[2] = [0]*len(non_interaction_df)

interaction_df = pd.DataFrame(interaction_list) 
interaction_df[2] = [1]*len(interaction_df)

df_concatenated = pd.concat([non_interaction_df, interaction_df], axis=0)
df_concatenated

            0        1  2
0     D013920  DB00396  0
1     D017449  DB00401  0
2     D013285  DB01399  0
3     D009157  DB00178  0
4     D003324  DB00876  0
...       ...      ... ..
4995  D019970  DB00714  1
4996  D058186  DB00364  1
4997  D009101  DB01069  1
4998  D006937  DB00722  1
4999  D011471  DB00443  1

[10000 rows x 3 columns]

In [19]:
df_concatenated.to_csv('labelssmall.csv')