## Loading Cdataset

In [1]:
import pandas as pd
import scipy.io
import numpy as np

In [27]:
# Load the MATLAB file
disease_data = scipy.io.loadmat('../../MBiRW/Datasets/CDatasets/DiseaseSimMat.mat')
disease_mat = disease_data['Wdd']
disease_names = []
with open('../../MBiRW/Datasets/CDatasets/DiseasesName', 'r') as f:
    disease_names = [line.strip() for line in f.readlines()]

In [32]:
# Load the MATLAB file
drug_data = scipy.io.loadmat('../../MBiRW/Datasets/CDatasets/DrugSimMat.mat')
drug_mat = drug_data['test']
drug_names = []
with open('../../MBiRW/Datasets/CDatasets/DrugsName', 'r') as f:
    drug_names = [line.strip() for line in f.readlines()]

In [33]:
disease_df = pd.DataFrame(disease_mat, index=disease_names, columns=disease_names)
drug_df = pd.DataFrame(drug_mat, index=drug_names, columns=drug_names)

In [35]:
disease_df.to_csv("../data/Cdata_Lssrl/Cdataset_disease.csv")
drug_df.to_csv("../data/Cdata_Lssrl/Cdataset_drug.csv")

In [49]:
drug_disease = pd.read_csv("../../MBiRW/Datasets/CDatasets/DrDiMat", sep="\t", header=None)

In [50]:
drug_disease = drug_disease.drop(columns=409)

In [52]:
drug_disease.index = drug_names
drug_disease.columns = disease_names

In [54]:
drug_disease.to_csv("../data/Cdata_Lssrl/Cdataset_drug_dis.csv")

In [56]:
drug_disease.info()

<class 'pandas.core.frame.DataFrame'>
Index: 663 entries, DB00014 to DB08907
Columns: 409 entries, D102100 to D608907
dtypes: int64(409)
memory usage: 2.1+ MB

In [76]:
(1 - (drug_disease.sum().sum())/(len(drug_names)*len(disease_names)))*100

99.06625806237484

## Cdataset 2

In [86]:
drug_mat = pd.read_csv("../../MBiRW/Datasets/DrugSimMat", sep=" ", header=None)
disease_mat = pd.read_csv("../../MBiRW/Datasets/DiseaseSimMat", sep=" ", header=None)

In [90]:
disease_names = []
with open('../../MBiRW/Datasets/DiseasesName', 'r') as f:
    disease_names = [line.strip() for line in f.readlines()]
drug_names = []
with open('../../MBiRW/Datasets/DrugsName', 'r') as f:
    drug_names = [line.strip() for line in f.readlines()]

In [91]:
disease_mat.index=disease_names
drug_mat.index=drug_names
disease_mat.columns=disease_names
drug_mat.columns=drug_names

In [93]:
disease_mat.to_csv("../data/Cdata_Lssrl/Cdatasetm_disease.csv")
drug_mat.to_csv("../data/Cdata_Lssrl/Cdatasetm_drug.csv")

In [96]:
drug_disease = pd.read_csv("../../MBiRW/Datasets/DiDrAMat", sep="\t", header=None)

In [97]:
drug_disease

,0,1,2,3,4,5,6,7,8,9,...,584,585,586,587,588,589,590,591,592,593
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,NaN
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
309,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
310,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
311,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
312,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,NaN

In [101]:
drug_disease = drug_disease.drop(columns=593)
drug_disease = drug_disease.T

In [102]:
drug_disease.index = drug_names
drug_disease.columns = disease_names

In [104]:
drug_disease.to_csv("../data/Cdata_Lssrl/Cdatasetm_drug_dis.csv")

In [105]:
drug_disease.info()

<class 'pandas.core.frame.DataFrame'>
Index: 593 entries, DB00007 to DB06287
Columns: 313 entries, D102100 to D608622
dtypes: int64(313)
memory usage: 1.4+ MB

In [106]:
(1 - (drug_disease.sum().sum())/(len(drug_names)*len(disease_names)))*100

98.95856343173014

## LSSRL dataset

In [4]:
disease_mat = pd.read_csv("../../LRSSL-master/disease_similarity.txt", sep="\t",index_col=0)

In [5]:
disease_mat

,D017088,D018784,D000014,D000022,D000038,D015823,D000151,D000152,D000163,D000172,...,D014777,D014839,D014860,D014901,D014917,D014927,D014946,D014987,D015043,D020096
1,,,,,,,,,,,,,,,,,,,,,
D017088,1.000000,0.087591,0.0000,0.044156,0.114014,0.131528,0.030227,0.0,0.593750,0.00000,...,0.237389,0.000000,0.121212,0.108434,0.103226,0.000000,0.172662,0.0,0.0,0.062338
D018784,0.087591,1.000000,0.0000,0.000000,0.776224,0.062827,0.030534,0.0,0.047745,0.00000,...,0.000000,0.038760,0.056338,0.016529,0.109091,0.052023,0.212766,0.0,0.0,0.080000
D000014,0.000000,0.000000,1.0000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.187500,0.000000,0.0,0.0,0.000000
D000022,0.044156,0.000000,0.0000,1.000000,0.000000,0.000000,0.000000,0.0,0.048433,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
D000038,0.114014,0.776224,0.0000,0.000000,1.000000,0.091837,0.044118,0.0,0.077519,0.00000,...,0.000000,0.044776,0.082569,0.026810,0.141176,0.067416,0.246575,0.0,0.0,0.092308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
D014927,0.000000,0.052023,0.1875,0.000000,0.067416,0.000000,0.000000,0.0,0.000000,0.00000,...,0.000000,0.036585,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.000000
D014946,0.172662,0.212766,0.0000,0.000000,0.246575,0.154639,0.074627,0.0,0.140992,0.00000,...,0.000000,0.000000,0.138889,0.048780,0.214286,0.000000,1.000000,0.0,0.0,0.125000
D014987,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.0,0.000000
D015043,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.04486,...,0.000000,0.000000,0.038462,0.000000,0.000000,0.000000,0.000000,0.0,1.0,0.000000
D020096,0.062338,0.080000,0.0000,0.000000,0.092308,0.056180,0.084746,0.0,0.051282,0.00000,...,0.000000,0.000000,0.050000,0.053412,0.078947,0.000000,0.125000,0.0,0.0,1.000000

In [6]:
disease_mat.to_csv("../data/Cdata_Lssrl/Lssrl_disease.csv")